version: "3.9"

services:
  redis:
    image: redis:7
    container_name: posshop_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: posshop_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posshop
      MYSQL_USER: posshop_user
      MYSQL_PASSWORD: posshop_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
